version: '3'

services:
  app:
    image: 181165410516.dkr.ecr.us-east-2.amazonaws.com/laraapp_repo
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    depends_on:
      - nginx

  nginx:
    image: nginx:1.26.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/sites-available/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
